/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
* Copyright  (C)  2010 - 2014 Goodix. Ltd.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/
static unsigned char* gtp_default_FW;


